---
title: "1-Regularized Multivariate"
author: "Mohammed Alrezq"
date: "2023-11-23"
output:
  word_document: default
  html_document: default
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, message=FALSE}
#install.packages("seminr")
library(seminr)
library(tidyverse)
library(psych)
library(lavaan)
library(semPlot)
library(regsem)
library("here")
library(corrplot)# to plot the correlation matrix 
library(glmnet)

```


# Download data 
```{r}
sem_plsData <- read.csv("sem_plsData.csv")
# remove extra column 
sem_plsData <- sem_plsData |>
  select(-1)
```

# Adding itmes for outcoems variabels by averaging 
```{r}
names(sem_plsData)
# Group the three outcomes and take their means 
sem_plsData <- sem_plsData |> 
  rowwise() |> 
  mutate(Avg_Transform_Success = mean(c_across(c(IMPL_SUCC_1, EMPL_SAT_9, ORG_IMP_12, STAKEH_ACC_4, EMPL_SKI_8, DEC_IMP_13, BUSI_IMP_11, EMPL_BEL_10))),
         Avg_Deploy_Success = mean(c_across(c(DEPLOY_6, ACT_INTG_7))),
         Avg_Improv_Success = mean(c_across(c(BUDG_COMP_2, TASK_COMP_3)))
         )

# Removes the itmes related to outcomes 
sem_plsData <- sem_plsData |> 
  select(-c(IMPL_SUCC_1, BUDG_COMP_2, TASK_COMP_3,  STAKEH_ACC_4, DEPLOY_6, ACT_INTG_7, EMPL_SKI_8, EMPL_SAT_9, EMPL_BEL_10, BUSI_IMP_11, ORG_IMP_12, DEC_IMP_13))
```

# Check for correlation 
```{r}
cor_matrix <- round(cor(sem_plsData, method = "spearman"), 2)
#write.csv(cor_matrix_DVs, "DVs_correlation_Sperman.csv")
# Plotting the correlation matrix
corrplot(cor_matrix, 
         method = "number", 
         #order = "hclust", # arranges the variables in a way that those with the highest similarities are closer to each other. 
         tl.col = "black", 
         #tl.srt = 45, 
         addCoef.col = "black",
         title =  "Correlation",
         line = -1)

#Note: overall correlation is okay less than 70%

str(sem_plsData)
sem_plsData$LD_SUP_1 <- as.numeric(sem_plsData$LD_SUP_1)
sem_plsData$EMP_ATT_3 <- as.numeric(sem_plsData$EMP_ATT_3)
sem_plsData$RES_AVL_4 <- as.numeric(sem_plsData$RES_AVL_4)
sem_plsData$LD_INV_5 <- as.numeric(sem_plsData$LD_INV_5)
sem_plsData$PRJ_SEL_6  <- as.numeric(sem_plsData$PRJ_SEL_6)
sem_plsData$LD_STL_9   <- as.numeric(sem_plsData$LD_STL_9)
sem_plsData$DAT_QLT_11  <- as.numeric(sem_plsData$DAT_QLT_11)
sem_plsData$EMP_ENG_12  <- as.numeric(sem_plsData$EMP_ENG_12)
sem_plsData$TOOL_AP_13  <- as.numeric(sem_plsData$TOOL_AP_13)
sem_plsData$CONTX_CUS_14  <- as.numeric(sem_plsData$CONTX_CUS_14)
sem_plsData$TRA_EDUC_18  <- as.numeric(sem_plsData$TRA_EDUC_18)
sem_plsData$WKF_SKL_19  <- as.numeric(sem_plsData$WKF_SKL_19)
sem_plsData$EXP_CON_20  <- as.numeric(sem_plsData$EXP_CON_20)

```

```{r}
#names(sem_plsData)
Y_Var <- sem_plsData[, c(19: 21)]
X_Var <- sem_plsData[ ,c(1:18)]

mutliv_lasso <- glmnet( 
                       as.matrix(X_Var),
                       as.matrix(Y_Var),
                       alpha = 1,
                       family = "mgaussian",
                       nlambda = 100)

par(mfrow = c(1,3))
plot(mutliv_lasso, xvar = "lambda")

# Cross validation to determine optimal lambda 
mutliv_lasso_cv <- cv.glmnet(as.matrix(X_Var),
                             as.matrix(Y_Var),
                             family = "mgaussian",# mgaussian is used for multivariate outcomes 
                             nfolds = 10,
                             type.measure = "mse")
# optimla (min) lmbda 
mutliv_lasso_cv$lambda.min
mutliv_lasso_cv$lambda.1se

coef(mutliv_lasso_cv)

# plot 
#par(mfrow = c(1,3))
plot(mutliv_lasso_cv)# Finla

# Finla model with optimal lmbda 
mutliv_lasso_optimla <- glmnet( 
                       as.matrix(X_Var),
                       as.matrix(Y_Var),
                       alpha = 1, # lasso 
                       family = "mgaussian",
                       lambda = mutliv_lasso_cv$lambda.min)


coef(mutliv_lasso_optimla)

```

# Transformational Success 
```{r}
names(sem_plsData)
TS_Y <- sem_plsData[, 19]

# Cross validation to determine optimal lambda 
set.seed(123)
TS_lasso_cv <- cv.glmnet(as.matrix(X_Var),
                             as.matrix(TS_Y),
                             family = "gaussian",# used for single outcome 
                             nfolds = 10,
                             type.measure = "mse")
# optimla (min) lmbda 
TS_lasso_cv$lambda.min
TS_lasso_cv$lambda.1se



# plot 
#par(mfrow = c(1,3))
plot(TS_lasso_cv)# Finla
coef(TS_lasso_cv) # based on the plot, the coef is based on lambda.1se. there are 9 variables and lambda.1se is close to 9 than lambda.min

# Finla model with optimal lmbda 
TS_lasso_optimla <- glmnet( 
                       as.matrix(X_Var),
                       as.matrix(TS_Y),
                       alpha = 1, # lasso 
                       family = "gaussian",
                       lambda = TS_lasso_cv$lambda.1se)

coef(TS_lasso_optimla)


```
# Deployment Success 
```{r}
names(sem_plsData)
DS_Y <- sem_plsData[, 20]

# Cross validation to determine optimal lambda 
set.seed(124)
DS_lasso_cv <- cv.glmnet(as.matrix(X_Var),
                             as.matrix(DS_Y),
                             family = "gaussian",# used for single outcome 
                             nfolds = 10,
                             type.measure = "mse")
# optimla (min) lmbda 
DS_lasso_cv$lambda.min
DS_lasso_cv$lambda.1se


# plot 
#par(mfrow = c(1,3))
plot(DS_lasso_cv)# Finla
coef(DS_lasso_cv)

# Finla model with optimal lmbda 
DS_lasso_optimal <- glmnet( 
                       as.matrix(X_Var),
                       as.matrix(DS_Y),
                       alpha = 1, # lasso 
                       family = "gaussian",
                       lambda = DS_lasso_cv$lambda.min)

coef(DS_lasso_optimal)




```

# Improvement Project Success 
```{r}
names(sem_plsData)
IPS_Y <- sem_plsData[, 21]

# Cross validation to determine optimal lambda
set.seed(147)
IPS_lasso_cv <- cv.glmnet(as.matrix(X_Var),
                             as.matrix(IPS_Y),
                             family = "gaussian",# used for single outcome 
                             nfolds = 10,
                             type.measure = "mse")
# optimla (min) lmbda 
IPS_lasso_cv$lambda.min
IPS_lasso_cv$lambda.1se


# plot 
#par(mfrow = c(1,3))
plot(IPS_lasso_cv)# Finla
coef(IPS_lasso_cv)
# Finla model with optimal lmbda 
IPS_lasso_optimla <- glmnet( 
                       as.matrix(X_Var),
                       as.matrix(IPS_Y),
                       alpha = 1, # lasso 
                       family = "gaussian",
                       lambda = IPS_lasso_cv$lambda.min)

coef(IPS_lasso_optimla)

```

```{r}
https://uc-r.github.io/regularized_regression#other

```

# Apply Regularization using all items (without EFA)
```{r}
reg_data <- read.csv("mean_data.csv")
reg_data <- reg_data |> 
  select(c(-1, -2))

names(reg_data)
# Identify DVs by taking the mean of the DVs 
reg_data <- reg_data |> 
  rowwise() |> 
  mutate(General_Success = mean(c_across(c(IMPL_SUCC_1, BUDG_COMP_2, TASK_COMP_3, STAKEH_ACC_4))),
         Embeddedness = mean(c_across(c(CULT_INTG_5, DEPLOY_6, ACT_INTG_7))),
         Org_Result = mean(c_across(c(ORG_IMP_12, BUSI_IMP_11, DEC_IMP_13))),
         Emp_Results = mean(c_across(c(EMPL_BEL_10, EMPL_SAT_9, EMPL_SKI_8))))

# remove items after groping thme  
reg_data <- reg_data |> 
  select(c(-1:-13))

summary(reg_data)

```

```{r}
library(parallel)
detectCores(logical = FALSE)
```

