---
title: "SEM-PLS"
author: "Mohammed Alrezq"
date: "2023-10-16"
output:
  word_document: default
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=FALSE}
#install.packages("seminr")
library(seminr)
library(tidyverse)
library(psych)
```


# Download data 
```{r}
sem_plsData <- read.csv("sem_plsData.csv")
# remove extra column 
sem_plsData <- sem_plsData |>
  select(-1)
names(sem_plsData)
```

# Rename items for ease of use in sempls model 
```{r}
sem_plsData <- sem_plsData |> 
  rename(TS1 = EMPL_SAT_9,
         TS2 = ORG_IMP_12,
         TS3 = STAKEH_ACC_4,
         TS4 = EMPL_SKI_8,
         TS5 = DEC_IMP_13,
         TS6 = BUSI_IMP_11,
         TS7 = IMPL_SUCC_1,
         TS8 = EMPL_BEL_10,
         DS1 = DEPLOY_6,
         DS2 = ACT_INTG_7,
         IPS1 = BUDG_COMP_2,
         IPS2 = TASK_COMP_3,
         IR1 = TOOL_AP_13,
         IR2 = CONTX_CUS_14,
         IR3 = EFT_REQ_15,
         IR4 = EMP_ENG_12,
         IR5 = EXP_CON_20,
         IR6 = CUS_IDEF_26,
         SII1 = TRA_EDUC_18,
         SII2 = PAT_RES_24,
         SII3 = WKF_SKL_19,
         SII4 = RES_AVL_4,
         SL1 = LD_STL_9,
         SL2 = LD_INV_5,
         SL3 = LD_SUP_1,
         MBI1 = DAT_QLT_11,
         MBI2 = DEF_MEA_7,
         MBI3 = PRJ_SEL_6,
         CA1 = EMP_ATT_3,
         CA2 = UND_CNG_22)

# Reorder the columns in the dataframe to run
sem_plsData <- sem_plsData |> 
  select(TS1, TS2, TS3, TS4, TS5, TS6, TS7, TS8, DS1, DS2, IPS1, IPS2, IR1, IR2, IR3, IR4, IR5, IR6, SII1, SII2, SII3, SII4, SL1, SL2, SL3, MBI1, MBI2, MBI3, CA1, CA2)
```


# Create measurment model (outer model)
```{r}
set.seed(545)
meas_model <- constructs(
  composite("Transformation_Success", multi_items("TS", 1:8), weights = mode_A),# mode A for reflective construct 
  composite("Deployment_Success", multi_items("DS", 1:2), weights = mode_A),
  composite("Improvement_Project_Success", multi_items("IPS", 1:2), weights = mode_A),
  composite("Improvement_Readiness", multi_items("IR", 1:6), weights = mode_A),
  composite("Sustainable_Improvement_Infrastructure", multi_items("SII", 1:4), weights = mode_A),
  composite("Supportive_Leadership", multi_items("SL", 1:3), weights = mode_A),
  composite("Measures_based_Improvement", multi_items("MBI", 1:3), weights = mode_A),
  composite("Change_Awareness", multi_items("CA", 1:2), weights = mode_A)
)

```

# Create structural model (inner model)
```{r}
set.seed(214)
struc_model <- relationships(
  paths(to = c("Transformation_Success", "Deployment_Success", "Improvement_Project_Success"),
         from = c("Improvement_Readiness", "Sustainable_Improvement_Infrastructure", "Supportive_Leadership", "Measures_based_Improvement", "Change_Awareness")))

  
```

# Estimate the model
```{r}
set.seed(123)
model_est <- estimate_pls(sem_plsData, measurement_model = meas_model, structural_model = struc_model,inner_weights = path_weighting)

model_est_summary <- summary(model_est)
str(model_est)

# max iteration: should be less than 300 max no. of iteration
model_est_summary$iterations # iteration =6 which is good 

#(1) indicator's reliability and 
model_est_summary$loadings
model_est_summary$loadings^2
#write.csv(model_est_summary$loadings, "SEM-PLS_indicator_reliability_squared.csv")

#(2) Internal consistency reliability
model_est_summary$reliability # the rhoA between alpha and rhoC
plot(model_est_summary$reliability)
#write.csv(model_est_summary$reliability, "Internal consistency reliability.csv")

#(3) Convergent validity
model_est_summary$reliability # all AVE above 0.5

#(4) Discriminant validity: the results are good
#(4.1)Fornell and Larcker
model_est_summary$validity$fl_criteria
#write.csv(model_est_summary$validity$fl_criteria, "discreminant_validity_FL.csv")

#(4.2)HTMT
model_est_summary$validity$htmt
#rite.csv(model_est_summary$validity$htmt, "discreminant_validity_HTMT.csv")

#(4.3)HTMT with boost for discriminant validity (by setting alpha = 0.10 = 90% 2-sided CI)
boost_summary_HTMT$bootstrapped_HTMT
#write.csv(boost_summary$bootstrapped_HTMT, "discreminant_validity_HTMTBoost2.csv")

#(4.4)cross loading for discriminant validity 
model_est_summary$validity$cross_loadings
#write.csv(model_est_summary$validity$cross_loadings, "discreminant_validity_Cross_Loading.csv")
#
model_est_summary$fSquare

plot(model_est)
```

# Bootstrap the model 
```{r}
#Bootstrap 
set.seed(147)
boost_model_HTMT <- bootstrap_model(seminr_model = model_est,
                               nboot = 10000,
                               cores = parallel::detectCores(), )

#Bootstrap for HTMT Discriminant 
boost_summary_HTMT <- summary(boost_model_HTMT, alpha = 0.10)

# Bootstrap for the signifiant coefficient paths 
set.seed(1470)
boost_model_paths <- bootstrap_model(seminr_model = model_est,
                               nboot = 10000,
                               cores = parallel::detectCores(), )

set.seed(001)
boost_summary_paths <- summary(boost_model_paths, alpha = 0.05)

plot(boost_model_paths)
```

# Structural model results 
```{r}
#(1) VIF from the estimated model NOT the boost model: this is VIF for items
model_est_summary$validity$vif_items
#write.csv(model_est_summary$validity$vif_items, "items_VIF.csv")

model_est_summary$vif_antecedents # WHY?this is VIF for constructs
#write.csv(model_est_summary$vif_antecedents, "VIF_score.csv")

#(2) Assess structural relationship (path coefficient) based on bootstrapping model 
boost_summary_paths$bootstrapped_paths
#write.csv(boost_summary_paths$bootstrapped_paths, "path_coefficient.csv")

#(3) assess model's explanatory power
model_est_summary$paths
#write.csv(model_est_summary$paths, "R-square.csv")

#(4) predictive model (not necessary)
predict_model <- predict_pls(
  model = model_est,
  technique = predict_EA,
  noFolds = 10,
  reps = 10
)
predict_summary <- summary(predict_model)


# analysis of the distribtuion to select RMSE or MEA
par(mfrow=c(4,4)) 
plot(predict_summary, indicator = "TS1")
plot(predict_summary, indicator = "TS2")
plot(predict_summary, indicator = "TS3")
plot(predict_summary, indicator = "TS4")
plot(predict_summary, indicator = "TS5")
plot(predict_summary, indicator = "TS6")
plot(predict_summary, indicator = "TS7")
plot(predict_summary, indicator = "TS8")
plot(predict_summary, indicator = "DS1")
plot(predict_summary, indicator = "DS2")
plot(predict_summary, indicator = "IPS1")
plot(predict_summary, indicator = "IPS2")

# the model has higher predective power by comparing RSEM of PLS out-of-sample metrics with LM out-of-sample metrics

#(5) Effect size 
model_est_summary$fSquare
#write.csv(model_est_summary$fSquare, "effect_size.csv")

#(total effect)
boost_summary_paths$bootstrapped_total_paths



library(semPlot)
semPaths(boost_summary_HTMT, whatLabels="est", title="Bootstrapped Model")

```




```{r}
# Generate the R code for plotting the heatmap using the data provided


# Load necessary libraries
library(ggplot2)
library(reshape2)


data <- data.frame(
  Category = c("TS1", "TS2", "TS3", "TS4", "TS5", "TS6", "TS7", "TS8", 
               "DS1", "DS2", 
               "IPS1", "IPS2", 
               "IR1", "IR2", "IR3", "IR4", "IR5", "IR6",
               "SII1", "SII2", "SII3", "SII4",
               "SL1", "SL2", "SL3",
               "MBI1", "MBI2", "MBI3",
               "CA1", "CA2"),
  Transformation_Success = c(0.81, 0.78, 0.68, 0.71, 0.69, 0.69, 0.72, 0.46, rep(NA, 22)),
  Deployment_Success = c(rep(NA, 8), 0.80, 0.87, rep(NA, 20)),
  Improvement_Project_Success = c(rep(NA, 10), 0.85, 0.85, rep(NA, 18)),
  Improvement_Readiness = c(rep(NA, 12), 0.77, 0.73, 0.67, 0.59, 0.49, 0.49, rep(NA, 12)),
  Sustainable_Improvement_Infrastructure = c(rep(NA, 18), 0.71, 0.66, 0.74, 0.59, rep(NA, 8)),
  Supportive_Leadership = c(rep(NA, 22), 0.84, 0.82, 0.80, rep(NA, 5)),
  Measures_based_Improvement = c(rep(NA, 25), 0.68, 0.86, 0.79, rep(NA, 2)),
  Change_Awareness = c(rep(NA, 28), 0.84, 0.58)
)

# Reshape the data for plotting
data_melted <- melt(data, id.vars = 'Category')

# Create the heatmap
ggplot(data_melted, aes(x = variable, y = Category, fill = value)) +
  geom_tile() +
  scale_fill_gradient(low = "blue", high = "red") +
  theme_minimal() +
  xlab("Success Measures") +
  ylab("Categories") +
  ggtitle("Heatmap of Various Success Measures")


```


```{r}
# Load necessary libraries
library(ggplot2)
library(reshape2)

# Data
data <- data.frame(
  Category = c("TS1", "TS2", "TS3", "TS4", "TS5", "TS6", "TS7", "TS8", 
               "DS1", "DS2", 
               "IPS1", "IPS2", 
               "IR1", "IR2", "IR3", "IR4", "IR5", "IR6",
               "SII1", "SII2", "SII3", "SII4",
               "SL1", "SL2", "SL3",
               "MBI1", "MBI2", "MBI3",
               "CA1", "CA2"),
  Transformation_Success = c(0.81, 0.78, 0.68, 0.71, 0.69, 0.69, 0.72, 0.46, rep(NA, 22)),
  Supportive_Leadership = c(rep(NA, 22), 0.84, 0.82, 0.80, rep(NA, 5)),
  Sustainable_Improvement_Infrastructure = c(rep(NA, 18), 0.71, 0.66, 0.74, 0.59, rep(NA, 8)),
  Measures_based_Improvement = c(rep(NA, 25), 0.68, 0.86, 0.79, rep(NA, 2)),
  Improvement_Readiness = c(rep(NA, 12), 0.77, 0.73, 0.67, 0.59, 0.49, 0.49, rep(NA, 12)),
  Improvement_Project_Success = c(rep(NA, 10), 0.85, 0.85, rep(NA, 18)),
  Deployment_Success = c(rep(NA, 8), 0.80, 0.87, rep(NA, 20)),
  Change_Awareness = c(rep(NA, 28), 0.84, 0.58)
)

# Reshape the data for plotting
data_melted <- melt(data, id.vars = 'Category')

# Create the heatmap
ggplot(data_melted, aes(x = variable, y = Category, fill = value)) +
  geom_tile() +
  scale_fill_gradient(low = "blue", high = "red") +
  theme_minimal() +
  xlab("Success Measures") +
  ylab("Categories") +
  ggtitle("Heatmap of Various Success Measures")

```

```{r}
# Ordering categories (example)
data$Category <- factor(data$Category, levels = data$Category[order(data$Transformation_Success, decreasing = TRUE)])

# Create the heatmap with a professional color palette and organized labels
ggplot(data_melted, aes(x = variable, y = Category, fill = value)) +
  geom_tile(color = "white") + # Adding borders to the tiles
  scale_fill_distiller(palette = "Spectral", direction = 1) + # Professional color palette
  theme_minimal() + # Clean theme
  theme(axis.text.x = element_text(angle = 45, hjust = 1), # Improve x-axis label legibility
        axis.title = element_text(size = 12, face = "bold"), # Bold axis titles
        plot.title = element_text(hjust = 0.5, size = 14, face = "bold")) + # Centered bold title
  labs(x = "Success Measures",
       y = "Categories",
       fill = "Score",
       title = "Professional Heatmap of Success Measures") +
  coord_fixed() # Keep aspect ratio square

# Print the plot
ggsave("heatmap_professional.png", width = 12, height = 10, dpi = 300)
```

```{r}
ggplot(data_melted, aes(x = variable, y = Category, fill = value)) +
  geom_tile(color = "white") + # Adding borders to the tiles
  scale_fill_distiller(palette = "Spectral", direction = 1, na.value = "transparent") + # Set NA color
  theme_minimal() + # Clean theme
  theme(axis.text.x = element_text(angle = 45, hjust = 1), # Improve x-axis label legibility
        axis.title = element_text(size = 12, face = "bold"), # Bold axis titles
        plot.title = element_text(hjust = 0.5, size = 14, face = "bold"), # Centered bold title
        panel.background = element_blank(), # Remove panel background
        #panel.grid.major = element_blank(), # Remove major grid lines
        panel.grid.minor = element_blank()) + # Remove minor grid lines
  labs(x = "Success Measures",
       y = "Categories",
       fill = "Score",
       title = "Professional Heatmap of Success Measures") +
  coord_fixed() # Keep aspect ratio square

# Print the plot
ggsave("heatmap_professional.png", width = 12, height = 10, dpi = 300)
```

